### ISSUE TITLE
Servers Remove in Tracker for a short time

### ISSUE THREAD

**Issue by TheWylot** [Alijkaz/IRMCTracker#9]
Hey, too many servers will remove for a 5-10 minutes on tracker and it will decrease the total minecraft players but server is on

**Comment by Alijkaz** [comment]
We're already aware of this problem,
I assume that this is Minecraft servers side problem that their firewalls blocks our tracker
There's a simple fix that I can implement for that problem and increase the checking time cycle (currently every 1min) to around ~5minutes but will make data much older so that I rather not doing that,
Will progressively look forward to fixing this problem...

**Comment by TheWylot** [comment]
> We're already aware of this problem,
> I assume that this is Minecraft servers side problem that their firewalls blocks our tracker
> There's a simple fix that I can implement for that problem and increase the checking time cycle (currently every 1min) to around ~5minutes but will make data much older so that I rather not doing that,
> Will progressively look forward to fixing this problem...

Also u can make a system that didnt block our protection system and firewall

**Comment by Alijkaz** [comment]
I'm pretty sure the issue is fixed by now,
Will do further investigation if the problem still persists
